services:
  n2n:
    restart: always
    container_name: n2n-sn
    image: theanony/n2n:3.0
    environment:
      TZ: Asia/Shanghai
    ports:
      - $N2N_SUPERNODE_PORT:9922
      - $N2N_SUPERNODE_PORT:9922/udp
    volumes:
      - ./community.list:/n2n/community.list:ro
    command: ["supernode", "-f", "-p", "9922", "-c", "/n2n/community.list"]
