CREATE DATABASE IF NOT EXISTS $SA_DB_NAME;
DROP USER IF EXISTS '${SA_DB_USER}'@'%';
CREATE USER '${SA_DB_USER}'@'%' IDENTIFIED BY '${SA_DB_PASSWD}';
GRANT ALL PRIVILEGES ON $SA_DB_NAME.* TO '${SA_DB_USER}'@'%';
FLUSH PRIVILEGES;
USE $SA_DB_NAME;