services:
  node_exporter:
    restart: unless-stopped
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro'
    networks:
      - zwnet
networks:
  zwnet:
    external: true
