CREATE DATABASE IF NOT EXISTS $GT_DB_NAME;
DROP USER IF EXISTS '${GT_DB_USER}'@'%';
CREATE USER '${GT_DB_USER}'@'%' IDENTIFIED BY '${GT_DB_PASSWD}';
GRANT ALL PRIVILEGES ON $GT_DB_NAME.* TO '${GT_DB_USER}'@'%';
FLUSH PRIVILEGES;