services:
  nfs:
    restart: unless-stopped
    container_name: nfs
    image: gists/nfs-server:2.6.4
    ports:
      # - 2049:2049
      # - 111:111
      - $NFS_DATA_PORT:2049
      - $NFS_RPC_PORT:111
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      NFS_DOMAIN: "*"
    volumes:
      - $SHARE_ROOT:/nfs-share
networks:
  zwnet:
    external: true