services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:3.8.3
    restart: unless-stopped
    ports:
      - "$CLOUDREVE_PORT:5212"
    volumes:
      - ./cloudreve/uploads:/cloudreve/uploads
      - ./cloudreve/conf.ini:/cloudreve/conf.ini
      - ./cloudreve/cloudreve.db:/cloudreve/cloudreve.db
      - ./cloudreve/avatar:/cloudreve/avatar
      - ./downloader-data:/data
    networks:
      - zwnet
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro:202209060423
    restart: unless-stopped
    environment:
      - RPC_SECRET=FTDzAgoL8Ebtb4QVhoDwxtUCh5t5mJPc
      - RPC_PORT=6800
      - PUID=0
      - PGID=0
    volumes:
      - ./aria2/config:/config
      - ./downloader-data:/data
    networks:
      - zwnet
networks:
  zwnet:
    external: true
